capture: capture.cpp
	g++ capture.cpp `pkg-config --cflags --libs opencv` -o capture
capture2: capture2.cpp
	g++ capture2.cpp `pkg-config --cflags --libs opencv` -o capture2
faceDetection: faceDetection.cpp
	g++ faceDetection.cpp `pkg-config --cflags --libs opencv` -o faceDetection

