capture: capture.cpp
	g++ capture.cpp `pkg-config --cflags --libs opencv` -o capture
capture2: capture2.cpp
	g++ capture2.cpp `pkg-config --cflags --libs opencv` -o capture2
faceDetection: faceDetection.cpp
	g++ faceDetection.cpp `pkg-config --cflags --libs opencv` -o faceDetection
ballDetection: ballDetection.cpp
	g++ ballDetection.cpp `pkg-config --cflags --libs opencv` -o ballDetection
ballTracking: ballTracking.cpp
	g++ ballTracking.cpp `pkg-config --cflags --libs opencv` -o ballTracking
ballTracking_bgrGray: ballTracking_bgrGray.cpp
	g++ ballTracking_bgrGray.cpp `pkg-config --cflags --libs opencv` -o ballTracking_bgrGray

ballTracking_ycrcbGray: ballTracking_ycrcbGray.cpp
	g++ ballTracking_ycrcbGray.cpp `pkg-config --cflags --libs opencv` -o ballTracking_ycrcbGray
ballTracking_ycrcb: ballTracking_ycrcb.cpp
	g++ ballTracking_ycrcb.cpp `pkg-config --cflags --libs opencv` -o ballTracking_ycrcb
